name: Test

on:
  workflow_dispatch:
  pull_request:
  
permissions:
  contents: read 

jobs:
  setup:
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    steps:
      - name: Install .NET to Device
        uses: actions/setup-dotnet@v4
        with:
          dotnet-version: "8.x.x"

      - name: Clone and Checkout the Repo
        uses: actions/checkout@v4
        with:
          submodules: recursive
          token: ${{ secrets.GITHUB_TOKEN }}
          clean: true

      - name: Run .NET Restore to reload NuGet Packages
        run: dotnet restore 

  test:
    needs: setup
    runs-on: ["self-hosted", "run-${{github.run_id}}"]
    steps:
      - name: Run Unit Tests using NUnit
        run: dotnet test -c Release --logger "console;verbosity=detailed" --filter "TestCategory!=Integration"